# Generated by Django 3.0.4 on 2020-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='业务线名称', max_length=32, verbose_name='业务线名称')),
                ('pid', models.IntegerField(db_index=True, help_text='上级业务线id', verbose_name='上级业务线id')),
                ('module_letter', models.CharField(help_text='业务线字母简称', max_length=32, verbose_name='业务线字母简称')),
            ],
            options={
                'db_table': 'resources_product',
                'ordering': ['id'],
            },
        ),
    ]
