# Generated by Django 3.0.4 on 2020-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('exec_host', models.CharField(max_length=200, null=True, verbose_name='执行主机ip')),
                ('model_name', models.CharField(choices=[('copy', 'copy'), ('ping', 'ping'), ('cron', 'cron'), ('service', 'service'), ('shell', 'shell'), ('script', 'script'), ('yum', 'yum'), ('setup', 'setup'), ('file', 'file'), ('group', 'group'), ('user', 'user'), ('stat', 'stat'), ('mount', 'mount')], max_length=30, null=True, verbose_name='模块名称')),
                ('model_args', models.CharField(max_length=100, null=True, verbose_name='模块参数')),
                ('detail_result', models.TextField(blank=True, null=True, verbose_name='执行结果详情')),
                ('status', models.CharField(choices=[('Y', '已执行'), ('R', '执行中'), ('N', '未执行')], default='N', max_length=1, verbose_name='执行状态')),
                ('result_view', models.CharField(max_length=500, null=True, verbose_name='执行结果')),
                ('is_visible', models.CharField(choices=[('Y', '可见'), ('N', '不可见')], default='Y', max_length=2, verbose_name='是否可见')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='任务创建时间')),
                ('exec_time', models.DateTimeField(auto_now=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'Ad-hoc任务',
                'verbose_name_plural': 'Ad-hoc任务',
                'db_table': 'ad_hoc_tasks',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('playbook', models.FileField(max_length=200, upload_to='playbook/%Y/%m', verbose_name='playbook文件')),
                ('detail_result', models.TextField(blank=True, null=True, verbose_name='执行结果详情')),
                ('status', models.CharField(choices=[('Y', '已执行'), ('R', '执行中'), ('N', '未执行')], default='N', max_length=1, verbose_name='执行状态')),
                ('result_view', models.CharField(max_length=500, null=True, verbose_name='执行结果')),
                ('is_visible', models.CharField(choices=[('Y', '可见'), ('N', '不可见')], default='Y', max_length=2, verbose_name='是否可见')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='任务创建时间')),
                ('exec_time', models.DateTimeField(auto_now=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'playbook_tasks',
                'ordering': ['-add_time'],
            },
        ),
    ]
