# Generated by Django 3.0.4 on 2020-03-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(db_index=True, default=None, help_text='资源名称', max_length=200, unique=True, verbose_name='资源名称')),
                ('manage_ip', models.GenericIPAddressField(db_index=True, default=None, help_text='管理IP', verbose_name='管理IP')),
                ('inner_ip', models.GenericIPAddressField(default=None, help_text='内网IP', verbose_name='内网IP')),
                ('add_time', models.DateTimeField(auto_now=True, help_text='添加时间', verbose_name='添加时间')),
                ('description', models.CharField(blank=True, default=None, help_text='描述', max_length=200, verbose_name='描述')),
            ],
            options={
                'db_table': 'resource',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default=None, help_text='资源类型名称', max_length=30, verbose_name='资源类型名称')),
                ('type_icon', models.CharField(default=None, help_text='资源图标', max_length=20, verbose_name='资源图标')),
            ],
            options={
                'db_table': 'resource_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default=None, help_text='用户名称', max_length=30, verbose_name='用户名称')),
                ('user_password', models.CharField(default=None, help_text='用户密码', max_length=255, verbose_name='用户名称')),
                ('port', models.IntegerField(default=22, help_text='端口', verbose_name='端口')),
                ('private_key', models.FileField(blank=True, default=None, max_length=200, null=True, upload_to='private_keys/', verbose_name='private keys')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建日期', verbose_name='创建日期')),
                ('last_login_time', models.DateTimeField(default=None, help_text='上次登录时间', null=True, verbose_name='上次登录时间')),
                ('is_superuser', models.IntegerField(choices=[(0, '是'), (1, '否')], default=0, help_text='是否为root账户', verbose_name='是否为root账户')),
                ('belong_resource', models.ForeignKey(help_text='所属资源', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='resources.Resource', verbose_name='所属资源')),
            ],
            options={
                'db_table': 'resource_users',
                'ordering': ['id'],
            },
        ),
    ]
