# Generated by Django 3.0.4 on 2020-03-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('products', '0002_auto_20200306_2349'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='belong_user',
            field=models.ForeignKey(help_text='添加用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(help_text='资源类型', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_type', to='resources.ResourceType', verbose_name='资源类型'),
        ),
        migrations.AddField(
            model_name='resource',
            name='server_purpose',
            field=models.ForeignKey(help_text='二级产品线', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_purpose', to='products.Product', verbose_name='二级产品线'),
        ),
        migrations.AddField(
            model_name='resource',
            name='service',
            field=models.ForeignKey(help_text='一级业务线', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='products.Product', verbose_name='一级业务线'),
        ),
    ]
