# Generated by Django 3.0.4 on 2020-03-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateWorkOrderFlowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type_name', models.CharField(help_text='类型名称', max_length=200, verbose_name='类型名称')),
                ('flow_type_status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, help_text='状态', verbose_name='工单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
            ],
            options={
                'db_table': 'template_work_order_flow_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateWorkOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='模板名称', max_length=200, unique=True, verbose_name='模板名称')),
                ('mode_status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, help_text='状态', verbose_name='状态')),
                ('model_create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('order_flow_type', models.ForeignKey(help_text='工单流程类型', on_delete=django.db.models.deletion.CASCADE, related_name='order_flow_type', to='workorder.TemplateWorkOrderFlowType', verbose_name='工单流程类型')),
            ],
            options={
                'db_table': 'template_work_order_model',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateWorkOrderProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='项目名称', max_length=200, verbose_name='项目名称')),
                ('project_info', models.CharField(help_text='项目信息', max_length=255, verbose_name='项目信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'db_table': 'template_work_order_project',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateWorkOrderTaskFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(db_index=True, help_text='流程名称', max_length=200, unique=True, verbose_name='流程名称')),
                ('flow_type', models.IntegerField(choices=[(0, '执行'), (1, '审核')], help_text='流程类型', verbose_name='流程类型')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now_add=True, help_text='上次修改时间', verbose_name='上次修改时间')),
            ],
            options={
                'db_table': 'template_work_order_flow',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderFlowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type_name', models.CharField(help_text='类型名称', max_length=200, verbose_name='类型名称')),
                ('flow_type_status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, help_text='状态', verbose_name='工单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
            ],
            options={
                'db_table': 'work_order_flow_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='模板名称', max_length=200, verbose_name='模板名称')),
                ('mode_status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, help_text='状态', verbose_name='状态')),
                ('model_create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('order_flow_type', models.ForeignKey(help_text='工单流程类型', on_delete=django.db.models.deletion.CASCADE, related_name='order_flow_type', to='workorder.WorkOrderFlowType', verbose_name='工单流程类型')),
            ],
            options={
                'db_table': 'work_order_model',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='项目名称', max_length=200, verbose_name='项目名称')),
                ('project_info', models.CharField(help_text='项目信息', max_length=255, verbose_name='项目信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'db_table': 'work_order_project',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(help_text='状态码', verbose_name='状态码')),
                ('status_name', models.CharField(help_text='状态名称', max_length=40, verbose_name='状态名称')),
                ('status_belong_table', models.CharField(help_text='所在表格', max_length=40, verbose_name='所在表格')),
            ],
            options={
                'db_table': 'work_order_status_code',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTaskFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_name', models.CharField(help_text='流程名称', max_length=200, verbose_name='流程名称')),
                ('flow_type', models.IntegerField(choices=[(0, '执行'), (1, '审核')], help_text='流程类型', verbose_name='流程类型')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now_add=True, help_text='上次修改时间', verbose_name='上次修改时间')),
            ],
            options={
                'db_table': 'work_order_flow',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, help_text='类型名称', max_length=200, unique=True, verbose_name='类型名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('type_status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, help_text='是否启用', verbose_name='是否启用')),
                ('link_project', models.ForeignKey(help_text='关联项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_project', to='workorder.WorkOrderProject', verbose_name='关联项目')),
            ],
            options={
                'db_table': 'work_order_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTaskFlowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_item_name', models.CharField(help_text='流程项名称', max_length=200, verbose_name='流程项名称')),
                ('exec_order', models.IntegerField(help_text='执行顺序', verbose_name='执行顺序')),
                ('ops_status', models.IntegerField(choices=[(1, '提交'), (2, '审核通过'), (3, '审核不通过'), (4, '审核转发'), (5, '确认执行'), (6, '执行确认不通过'), (7, '延期执行'), (8, '执行完成'), (9, '执行转发'), (10, '用户确认不通过'), (11, '关闭'), (12, '重走流程'), (13, '重新编辑'), (14, '撤回工单'), (15, '回复')], help_text='状态', null=True, verbose_name='状态')),
                ('belong_flow', models.ForeignKey(help_text='所属流程名称', on_delete=django.db.models.deletion.CASCADE, related_name='belong_flow', to='workorder.WorkOrderTaskFlow', verbose_name='所属流程名称')),
                ('exec_user', models.ForeignKey(help_text='执行/审核用户', on_delete=django.db.models.deletion.CASCADE, related_name='exec_user', to=settings.AUTH_USER_MODEL, verbose_name='执行/审核用户')),
            ],
            options={
                'db_table': 'work_order_flow_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_task_id', models.CharField(help_text='工单ID', max_length=40, verbose_name='工单ID')),
                ('order_title', models.CharField(help_text='工单标题', max_length=100, verbose_name='工单标题')),
                ('order_env_type', models.CharField(default=None, help_text='平台类型', max_length=20, verbose_name='平台类型')),
                ('order_purpose', models.TextField(help_text='工单需求', verbose_name='工单需求')),
                ('order_files', models.FileField(default=None, max_length=200, upload_to='work_order_files/%Y/%m', verbose_name='工单上传文件')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('order_result', models.TextField(default=None, help_text='工单结果', null=True, verbose_name='工单结果')),
                ('order_status', models.IntegerField(choices=[(1, '待提交'), (2, '审核中'), (3, '执行人确认中'), (4, '执行人执行中'), (5, '执行人延期执行中'), (6, '执行完成,用户确认中'), (7, '审核驳回,等待用户确认'), (8, '执行驳回,等待用户确认'), (9, '用户确认不通过,等待执行重做'), (10, '完成关闭'), (11, '驳回关闭'), (12, '撤销关闭')], default=1, help_text='工单状态', verbose_name='工单状态')),
                ('created_user', models.ForeignKey(help_text='创建用户', on_delete=django.db.models.deletion.CASCADE, related_name='created_user', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
                ('current_audit_user', models.ForeignKey(help_text='当前审核用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_audit_user', to=settings.AUTH_USER_MODEL, verbose_name='当前审核用户')),
                ('current_exec_user', models.ForeignKey(help_text='当前执行用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_exec_user', to=settings.AUTH_USER_MODEL, verbose_name='当前执行用户')),
                ('order_model', models.ForeignKey(default=None, help_text='工单模板 实例', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_model', to='workorder.WorkOrderModel', verbose_name='工单模板 实例')),
                ('order_products', models.ForeignKey(help_text='工单项目环境', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='工单项目环境')),
                ('template_order_model', models.ForeignKey(help_text='工单模板模型 ', on_delete=django.db.models.deletion.CASCADE, related_name='template_order_model', to='workorder.TemplateWorkOrderModel', verbose_name='工单模板模型')),
            ],
            options={
                'db_table': 'work_order_task',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ops_status', models.IntegerField(choices=[(1, '提交'), (2, '审核通过'), (3, '审核不通过'), (4, '审核转发'), (5, '确认执行'), (6, '执行确认不通过'), (7, '延期执行'), (8, '执行完成'), (9, '执行转发'), (10, '用户确认不通过'), (11, '关闭'), (12, '重走流程'), (13, '重新编辑'), (14, '撤回工单'), (15, '回复')], help_text='操作状态', verbose_name='操作状态')),
                ('ops_reply_content', models.TextField(blank=True, help_text='回复内容', null=True, verbose_name='回复内容')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
                ('ops_user', models.ForeignKey(help_text='执行用户', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_ops_user', to=settings.AUTH_USER_MODEL, verbose_name='执行用户')),
                ('work_order', models.ForeignKey(help_text='工单名称', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_task', to='workorder.WorkOrderTask', verbose_name='工单名称')),
            ],
            options={
                'db_table': 'work_order_operation',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='order_type',
            field=models.ForeignKey(help_text='工单类型', on_delete=django.db.models.deletion.CASCADE, related_name='order_type', to='workorder.WorkOrderType', verbose_name='工单类型'),
        ),
        migrations.AddField(
            model_name='workorderflowtype',
            name='task_audit_flow',
            field=models.ForeignKey(help_text='工单审核流程', on_delete=django.db.models.deletion.CASCADE, related_name='audit_flow', to='workorder.WorkOrderTaskFlow', verbose_name='工单审核流程'),
        ),
        migrations.AddField(
            model_name='workorderflowtype',
            name='task_exec_flow',
            field=models.ForeignKey(help_text='工单执行流程', on_delete=django.db.models.deletion.CASCADE, related_name='exec_flow', to='workorder.WorkOrderTaskFlow', verbose_name='工单执行流程'),
        ),
        migrations.CreateModel(
            name='TemplateWorkOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(db_index=True, help_text='类型名称', max_length=200, unique=True, verbose_name='类型名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('type_status', models.IntegerField(choices=[(0, '禁用'), (1, '启用')], default=1, help_text='是否启用', verbose_name='是否启用')),
                ('link_project', models.ForeignKey(help_text='关联项目', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_project', to='workorder.TemplateWorkOrderProject', verbose_name='关联项目')),
            ],
            options={
                'db_table': 'template_work_order_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateWorkOrderTaskFlowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_item_name', models.CharField(help_text='流程项名称', max_length=200, verbose_name='流程项名称')),
                ('exec_order', models.IntegerField(help_text='执行顺序', verbose_name='执行顺序')),
                ('ops_status', models.IntegerField(choices=[(1, '提交'), (2, '审核通过'), (3, '审核不通过'), (4, '审核转发'), (5, '确认执行'), (6, '执行确认不通过'), (7, '延期执行'), (8, '执行完成'), (9, '执行转发'), (10, '用户确认不通过'), (11, '关闭'), (12, '重走流程'), (13, '重新编辑'), (14, '撤回工单'), (15, '回复')], help_text='状态', null=True, verbose_name='状态')),
                ('belong_flow', models.ForeignKey(help_text='所属流程名称', on_delete=django.db.models.deletion.CASCADE, related_name='belong_flow', to='workorder.TemplateWorkOrderTaskFlow', verbose_name='所属流程名称')),
                ('exec_user', models.ForeignKey(help_text='执行/审核用户', on_delete=django.db.models.deletion.CASCADE, related_name='template_exec_user', to=settings.AUTH_USER_MODEL, verbose_name='执行/审核用户')),
            ],
            options={
                'db_table': 'template_work_order_flow_item',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='templateworkordermodel',
            name='order_type',
            field=models.ForeignKey(help_text='工单类型', on_delete=django.db.models.deletion.CASCADE, related_name='order_type', to='workorder.TemplateWorkOrderType', verbose_name='工单类型'),
        ),
        migrations.AddField(
            model_name='templateworkorderflowtype',
            name='task_audit_flow',
            field=models.ForeignKey(help_text='工单审核流程', on_delete=django.db.models.deletion.CASCADE, related_name='task_audit_flow', to='workorder.TemplateWorkOrderTaskFlow', verbose_name='工单审核流程'),
        ),
        migrations.AddField(
            model_name='templateworkorderflowtype',
            name='task_exec_flow',
            field=models.ForeignKey(help_text='工单执行流程', on_delete=django.db.models.deletion.CASCADE, related_name='task_exec_flow', to='workorder.TemplateWorkOrderTaskFlow', verbose_name='工单执行流程'),
        ),
    ]
